server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG


#  Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이
#  ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하고 있다!

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages
  security:
    user:
      name: user
      password: 1234


management:
  endpoints:
    web:
      exposure:
        include: "*"
